[avaliacao_atendimento]
exten => h,1,Set(AVALIACAO=0)
    same => n,Macro(hangupcall)

exten => s,1,NoOp(<< Avaliacao de atendimento >>)

    same => n,Set(DIR_PHONEVOX=phonevox-customs)

    same => n,Set(AVALIACAO=1)
    same => n,Set(CAUSADOR=atendente)
    same => n,Set(TIMEOUT(digit)=3)
    same => n,Set(atendente=${CONNECTEDLINE(num)})
    same => n,Background(${DIR_PHONEVOX}/avaliacao_atendimento)
    same => n,WaitExten(10)
    same => n,Background(${DIR_PHONEVOX}/avaliacao_atendimento)
    same => n,WaitExten(10)
    same => n,Hangup()

exten => 0,1,NoOp(<< Nota do cliente inferior a 1 >>)
    same => n,Goto(${CONTEXT},1,1)

exten => _[1-5],1,NoOp(<< Nota do cliente ${CALLERID(num)} para o atendente ${atendente}: N${EXTEN} >>)
    same => n,Set(nota=${EXTEN})
    same => n,GotoIf($["${nota}" = "1"]?um)
    same => n,GotoIf($["${nota}" = "2"]?dois)
    same => n,GotoIf($["${nota}" = "3"]?tres)
    same => n,GotoIf($["${nota}" = "4"]?quatro)
    same => n,GotoIf($["${nota}" = "5"]?cinco)
    same => n(um),AGI(${DIR_PHONEVOX}/insert_note.php,"Muito Insatisfeito","${CALLERID(num)}","${nota}","${atendente}","${UNIQUEID}","${EMPRESA}")
    same => n,Goto(agradece)
    same => n(dois),AGI(${DIR_PHONEVOX}/insert_note.php,"Insatisfeito","${CALLERID(num)}","${nota}","${atendente}","${UNIQUEID}","${EMPRESA}")
    same => n,Goto(agradece)
    same => n(tres),AGI(${DIR_PHONEVOX}/insert_note.php,"Pouco Satisfeito","${CALLERID(num)}","${nota}","${atendente}","${UNIQUEID}","${EMPRESA}")
    same => n,Goto(agradece)
    same => n(quatro),AGI(${DIR_PHONEVOX}/insert_note.php,"Satisfeito","${CALLERID(num)}","${nota}","${atendente}","${UNIQUEID}","${EMPRESA}")
    same => n,Goto(agradece)
    same => n(cinco),AGI(${DIR_PHONEVOX}/insert_note.php,"Muito Satisfeito","${CALLERID(num)}","${nota}","${atendente}","${UNIQUEID}","${EMPRESA}")
    same => n(agradece),Playback(${DIR_PHONEVOX}/agradece_avaliacao)
    same => n,Hangup()

exten => _[6-9],1,NoOp(<< Nota do cliente superior a 5 >>)
    same => n,Goto(${CONTEXT},5,1)

exten => _ZX,1,Goto(${CONTEXT},5,1)

exten => i,1,NoOp(<< Digito nao configurado >>)
    same => n,Hangup()